# Generated by Django 6.0.4 on 2026-04-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kozUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom et prenom')),
                ('telephone', models.CharField(max_length=30, verbose_name='Numéro de telephone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse de livraison')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_dernière_connexion', models.DateField(auto_now=True, verbose_name=' dernière connexion')),
                ('est_actif', models.BooleanField(default=True, verbose_name='compte actif')),
            ],
            options={
                'verbose_name': 'kozUser',
                'verbose_name_plural': 'kozUsers',
                'db_table': 'kozUsers',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
