# Generated by Django 6.0.4 on 2026-05-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='kozUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom et prenom')),
                ('telephone', models.CharField(max_length=30, verbose_name='Numéro de telephone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse de livraison')),
                ('pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays de résidence')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville de résidence')),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, null=True, verbose_name='Genre')),
                ('profession_choisie', models.CharField(blank=True, choices=[('employe', 'Employé'), ('chef_d_equipe', "Chef d'équipe"), ('gerant', 'Gérant'), ('etudiant', 'Étudiant'), ('autre', 'Autre')], null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('commercial', 'Commercial'), ('directeur', 'Directeur')], default='client', max_length=30)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_dernière_connexion', models.DateField(auto_now=True, verbose_name=' dernière connexion')),
                ('est_actif', models.BooleanField(default=True, verbose_name='compte actif')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('assigned_commercial', models.ForeignKey(blank=True, limit_choices_to={'role': 'commercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Commercial assigné')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'kozUser',
                'verbose_name_plural': 'kozUsers',
                'db_table': 'kozUsers',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
