# Generated by Django 6.0.4 on 2026-04-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kozuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kozuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kozuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
