# Generated by Django 6.0.4 on 2026-04-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_kozuser_is_active_kozuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kozuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('commercial', 'Commercial'), ('directeur', 'Directeur')], default='client', max_length=30),
        ),
    ]
