# Generated by Django 6.0.4 on 2026-04-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_kozuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kozuser',
            name='credit_lead',
        ),
    ]
