# Generated by Django 6.0.4 on 2026-04-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_kozuser_credit_lead'),
        ('leads_app', '0002_demande_financement_delete_creditleads'),
    ]

    operations = [
        migrations.AddField(
            model_name='kozuser',
            name='demande_financement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_demande', to='leads_app.demande_financement', verbose_name='Demande de financement associée'),
        ),
        migrations.AddField(
            model_name='kozuser',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='kozuser',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays de résidence'),
        ),
        migrations.AddField(
            model_name='kozuser',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kozuser',
            name='profession_choisie',
            field=models.CharField(blank=True, choices=[('employe', 'Employé'), ('chef_d_equipe', "Chef d'équipe"), ('gerant', 'Gérant'), ('etudiant', 'Étudiant'), ('autre', 'Autre')], null=True),
        ),
        migrations.AddField(
            model_name='kozuser',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville de résidence'),
        ),
    ]
