# Generated by Django 6.0.4 on 2026-04-29 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_kozuser_demande_financement_kozuser_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kozuser',
            name='assigned_commercial',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'commercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Commercial assigné'),
        ),
    ]
