# Generated by Django 6.0.4 on 2026-05-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0001_initial'),
        ('paiement_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='paiements',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_paiement', to='paiement_app.paiement'),
        ),
        migrations.AddField(
            model_name='panier',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.panier'),
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='order_app.panier'),
        ),
    ]
