# Generated by Django 6.0.4 on 2026-05-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicul_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='marque',
        ),
        migrations.CreateModel(
            name='Vehicul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=0, max_digits=12)),
                ('kilometrage', models.IntegerField()),
                ('carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Electrique')], max_length=20)),
                ('image_principale', models.ImageField(upload_to='vehicules/')),
                ('disponible', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicul', to='vehicul_app.marque')),
            ],
        ),
    ]
