# Generated by Django 6.0.4 on 2026-05-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0002_alter_offre_vehicule_propose'),
        ('leads_app', '0004_demande_financement_vehicul_interested_and_more'),
        ('vehicul_app', '0002_remove_vehicle_marque_vehicul'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
