# Generated by Django 6.0.4 on 2026-04-12 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicul_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_vehicule', models.DecimalField(decimal_places=0, max_digits=12)),
                ('apport_demande', models.DecimalField(decimal_places=0, max_digits=12)),
                ('montant_finance', models.DecimalField(decimal_places=0, max_digits=12)),
                ('duree_mois', models.IntegerField()),
                ('mensualite', models.DecimalField(decimal_places=0, max_digits=12)),
                ('taux_interet', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('frais_dossier', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('frais_garantie', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_du', models.DecimalField(blank=True, decimal_places=0, max_digits=12)),
                ('statut', models.CharField(choices=[('brouillon', 'En cours de rédaction'), ('envoyee', 'Envoyée au client'), ('acceptee', 'Acceptée par le client'), ('refusee', 'Refusée par le client'), ('expiree', 'Offre expirée')], default='brouillon', max_length=30)),
                ('signature_client', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('date_expiration', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to=settings.AUTH_USER_MODEL)),
                ('vehicule_propose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='vehicul_app.vehicle')),
            ],
        ),
    ]
