# Generated by Django 6.0.4 on 2026-05-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0001_initial'),
        ('vehicul_app', '0002_remove_vehicle_marque_vehicul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='vehicule_propose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='vehicul_app.vehicul'),
        ),
    ]
