# Generated by Django 6.0.4 on 2026-04-12 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('cni', "Carte d'identité"), ('passeport', 'Passeport'), ('justificatif_domicile', 'Justificatif de domicile'), ('quittance de salaire', 'Quittance de salaire'), ('releve_bancaire', 'Relevé bancaire'), ('contrat_travail', 'Contrat de travail'), ('autre', 'Autre document')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de téléchargement'), ('telecharge', 'Téléchargé - En cours de verification'), ('valide', 'Validé par le commercial'), ('rejete', 'Rejeté')], default='en_attente', max_length=30)),
                ('commentaire_rejet', models.TextField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('est_client', models.BooleanField(default=True)),
                ('lu', models.BooleanField(default=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('immatriculation', models.CharField(max_length=20)),
                ('kilometrage_actuel', models.IntegerField()),
                ('origine', models.CharField(choices=[('koz', 'Acheté chez KOZ'), ('externe', 'Véhicule extérieur')], default='externe', max_length=20)),
                ('type_maintenance', models.CharField(choices=[('vidange', 'Vidange'), ('revision', 'Révision complète'), ('pneumatiques', 'Pneumatiques'), ('freins', 'Freins/plaquettes'), ('climatisation', 'Climatisation'), ('batterie', 'Batterie'), ('courroie', 'Courroie de distribution'), ('autre', 'Autre')], max_length=30)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('date_prochaine', models.DateField()),
                ('date_derniere', models.DateField(blank=True, null=True)),
                ('kilometrage_prochain', models.IntegerField()),
                ('kilometrage_dernier', models.IntegerField(blank=True, null=True)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('montant_reel', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('confirmee', 'Confirmée par client'), ('en_cours', 'En cours'), ('effectuee', 'Effectuée'), ('depassee', 'Dépassée (non faite)'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('rappel_envoye', models.BooleanField(default=False)),
                ('date_rappel', models.DateField(blank=True, null=True)),
                ('sms_envoye', models.BooleanField(default=False)),
                ('email_envoye', models.BooleanField(default=False)),
                ('notes_client', models.TextField(blank=True)),
                ('notes_technicien', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to=settings.AUTH_USER_MODEL)),
                ('effectue_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'commercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_prochaine'],
                'indexes': [models.Index(fields=['statut', 'date_prochaine'], name='client_app__statut_c698d8_idx'), models.Index(fields=['origine', 'statut'], name='client_app__origine_ca4caa_idx'), models.Index(fields=['priorite', 'statut'], name='client_app__priorit_91c3b1_idx')],
            },
        ),
    ]
