# Generated by Django 6.0.4 on 2026-05-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cni_passeport', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='CNI ou Passeport')),
                ('justificatif_domicile', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Justificatif de domicile')),
                ('quittance_salaire', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Quittance de salaire')),
                ('relevé_bancaire', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Relevé bancaire')),
                ('contrat_travail', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Contrat de travail')),
                ('avis_imposition', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name="Avis d'imposition")),
                ('autres', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Autres documents')),
                ('statut_dossier', models.CharField(choices=[('envoye', 'envoyés'), ('incomplet', 'Dossier incomplet'), ('complet', 'Dossier complet'), ('verification', 'En cours de vérification'), ('valide', 'Documents validés'), ('rejete', 'Documents rejetés')], default='envoye', max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('demande_financement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads_app.demande_financement')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('immatriculation', models.CharField(max_length=20)),
                ('kilometrage_actuel', models.IntegerField()),
                ('origine', models.CharField(choices=[('koz', 'Acheté chez KOZ'), ('externe', 'Véhicule extérieur')], default='externe', max_length=20)),
                ('type_maintenance', models.CharField(choices=[('vidange', 'Vidange'), ('revision', 'Révision complète'), ('pneumatiques', 'Pneumatiques'), ('freins', 'Freins/plaquettes'), ('climatisation', 'Climatisation'), ('batterie', 'Batterie'), ('courroie', 'Courroie de distribution'), ('autre', 'Autre')], max_length=30)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('date_prochaine', models.DateField()),
                ('date_derniere', models.DateField(blank=True, null=True)),
                ('kilometrage_prochain', models.IntegerField()),
                ('kilometrage_dernier', models.IntegerField(blank=True, null=True)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('montant_reel', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('confirmee', 'Confirmée par client'), ('en_cours', 'En cours'), ('effectuee', 'Effectuée'), ('depassee', 'Dépassée (non faite)'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('rappel_envoye', models.BooleanField(default=False)),
                ('date_rappel', models.DateField(blank=True, null=True)),
                ('sms_envoye', models.BooleanField(default=False)),
                ('email_envoye', models.BooleanField(default=False)),
                ('notes_client', models.TextField(blank=True)),
                ('notes_technicien', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to=settings.AUTH_USER_MODEL)),
                ('effectue_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'commercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_prochaine'],
                'indexes': [models.Index(fields=['statut', 'date_prochaine'], name='client_app__statut_c698d8_idx'), models.Index(fields=['origine', 'statut'], name='client_app__origine_ca4caa_idx'), models.Index(fields=['priorite', 'statut'], name='client_app__priorit_91c3b1_idx')],
            },
        ),
    ]
