# Generated by Django 6.0.4 on 2026-04-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_documents_demande_financement_alter_documents_client_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
