# Generated by Django 6.0.4 on 2026-05-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicul_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='demande_financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financement_type', models.CharField(blank=True, choices=[('maison', 'Maison'), ('externe', 'Externe')], max_length=50, null=True)),
                ('financement_par', models.CharField(blank=True, choices=[('fidelis,', 'Fidelis'), ('alios', 'Alios')], max_length=50, null=True)),
                ('other_Vehicul_interested', models.CharField(blank=True, null=True)),
                ('apport', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('duree_mois', models.IntegerField(default=36)),
                ('mensualite_simulee', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('revenus_mensuel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('etape', models.CharField(choices=[('nouvelle', 'Nouvelle demande'), ('en_attente', 'en attente de document'), ('demande_accordee', 'Demande accordée'), ('demand_refusee', 'Demande Refusé')], default='nouvelle', max_length=20)),
                ('notes_commercial', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('Vehicul_interested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_financement', to='vehicul_app.vehicul', verbose_name="Véhicule d'intérêt")),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_financement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevisLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('other_Vehicul_interested', models.CharField(blank=True, null=True)),
                ('traited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Vehicul_interested_in_catalogue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Vehicul_interested', to='vehicul_app.vehicul')),
            ],
        ),
    ]
