# Generated by Django 6.0.4 on 2026-04-12 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicul_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('other_vehicle_interested', models.CharField(blank=True, null=True)),
                ('apport', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('duree_mois', models.IntegerField(default=36)),
                ('mensualite_simulee', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('profession_choisie', models.CharField(blank=True, choices=[('employe', 'Employé'), ('chef_d_equipe', "Chef d'équipe"), ('gerant', 'Gérant'), ('etudiant', 'Étudiant'), ('autre', 'Autre')])),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('revenus_mensuel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('etape', models.CharField(choices=[('nouveau', 'Nouveau lead'), ('contact_etabli', 'Contact établi'), ('docs_envoye', 'Pièces envoyées'), ('etude_en_cours', 'Etude en cours'), ('offre_emise', 'offre émise'), ('accepte', 'Accepté'), ('rejete', 'Rejeté')], default='nouveau', max_length=20)),
                ('notes_commercial', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('Vehicle_interested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='vehicul_app.vehicle')),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'directeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads_as_manager', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'commercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role:': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_credit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevisLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('other_vehicle_interested', models.CharField(blank=True, null=True)),
                ('traited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Vehicle_interested_in_catalogue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Vehicle_interested', to='vehicul_app.vehicle')),
            ],
        ),
    ]
