# Generated by Django 6.0.4 on 2026-04-27 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_kozuser_credit_lead'),
        ('leads_app', '0001_initial'),
        ('vehicul_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='demande_financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financement_par', models.CharField(blank=True, choices=[('fidelis,', 'Fidelis'), ('Alios', 'Alios')], max_length=50, null=True)),
                ('other_vehicle_interested', models.CharField(blank=True, null=True)),
                ('apport', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('duree_mois', models.IntegerField(default=36)),
                ('mensualite_simulee', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('revenus_mensuel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('etape', models.CharField(choices=[('nouveau_dossier', 'Nouveau dossier'), ('en_attente', 'en attente de document client'), ('dossier_complet', 'Dossier complet'), ('dossier_accepte', 'Dossier Accepté'), ('dossier_rejete', 'Dossier Refusé')], default='nouveau', max_length=20)),
                ('notes_commercial', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('Vehicle_interested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_financement', to='vehicul_app.vehicle', verbose_name="Véhicule d'intérêt")),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'directeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads_as_manager', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'commercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_fin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CreditLeads',
        ),
    ]
