# Generated by Django 6.0.4 on 2026-05-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0002_demande_financement_delete_creditleads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande_financement',
            old_name='other_vehicle_interested',
            new_name='other_Vehicul_interested',
        ),
        migrations.RenameField(
            model_name='devisleads',
            old_name='other_vehicle_interested',
            new_name='other_Vehicul_interested',
        ),
        migrations.RemoveField(
            model_name='demande_financement',
            name='Vehicle_interested',
        ),
        migrations.RemoveField(
            model_name='devisleads',
            name='Vehicle_interested_in_catalogue',
        ),
    ]
