# Generated by Django 6.0.4 on 2026-05-06 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0003_rename_other_vehicle_interested_demande_financement_other_vehicul_interested_and_more'),
        ('vehicul_app', '0002_remove_vehicle_marque_vehicul'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_financement',
            name='Vehicul_interested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_financement', to='vehicul_app.vehicul', verbose_name="Véhicule d'intérêt"),
        ),
        migrations.AddField(
            model_name='devisleads',
            name='Vehicul_interested_in_catalogue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Vehicul_interested', to='vehicul_app.vehicul'),
        ),
    ]
