# Generated by Django 6.0.4 on 2026-04-12 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('carte_ligdicash', 'Carte Bancaire(ligdicash)'), ('mobile_ligdicash', 'Mobile Money (Ligdicash)')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statu', models.CharField(choices=[('en_attente', 'Attente'), ('reussi', 'Reussi'), ('echec', 'Echoué'), ('annule', 'Annule')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ligdicash_transaction_id', models.CharField(blank=True, max_length=100)),
                ('ligdicash_phone', models.CharField(blank=True, max_length=20)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='order_app.commande')),
            ],
        ),
    ]
